### ISSUE TITLE
Bug with text rotation

### ISSUE THREAD

**Issue by Yu-Leo** [Yu-Leo/MemMakerBot#1]
Коммит: [25d70f6](https://github.com/Yu-Leo/MemMakerBot/commit/25d70f60179c571accb9f28b32687a9ed85ffbf2)
При использовании повернутого текста, текст смещается относительно заданных координат.

Как обнажить этот баг:
1. "1) Создать мем"
2. "Выбрать шаблон"
3. 100
4. "Использовать этот шаблон"
5. 123
6. "По центру картинки"
7. "180"
8. "Использовать текущий"

На получившемся изображении будет два раза выведено "123". Один раз - с углом наклона 0 градусов, по центру картинки. Второй раз - с углом наклона 180 градусов, со смещением относительно центра.

Необходимо сделать так, чтобы повернутый на 180 градусов текст выводился на месте того, который повернут на 0 градусов.

Аналогичная проблема возникает и при других картинках, другом тексте, и других настройках расположения и угла поворота текста (кроме угла в 0 градусов)

**Comment by ASDF2357** [comment]
Добавлен файл **mmbpictur (для проверки)**. Баг исправлен.

**Comment by Yu-Leo** [comment]
Баг исправлен. Коммит: [9cc7ecc](https://github.com/Yu-Leo/MemMakerBot/commit/9721e9e8923602719806da773ff0daae7d5396e8)
